// https://github.com/actions/checkout
[plugin.workflows.checkout]
uses = "actions/checkout@v4"

// https://github.com/actions/setup-java
[plugin.workflows.setupJava]
uses = "actions/setup-java@v4"
with = { distribution = "temurin", java-version = "17" }
